woowa-techcamp-2021/cashbook-11

.gitignore
server/package.json
server/src/app.js
server/src/config/config_sample.json
server/src/constants/error.js
server/src/constants/success.js
server/src/errors/custom-error.js
server/src/middlewares/decode-jwt.js
server/src/middlewares/error-handler.js
server/src/models/index.js
server/src/models/user.js
server/src/routes/index.js
server/src/routes/user-router.js
server/src/services/user-service.js
server/src/utils/bcrypt.js
server/src/utils/jwt.js

> **모든 작업은 페어프로그래밍을 통해 진행했습니다.**
백엔드 프로젝트 구조 잡기 완료
express 서버와 sequelize 연동, 필요한 미들웨어 추가등 기본적인 백엔드 프로젝트 구조를 잡았습니다. 
Postman 을 통한 API 테스트까지 진행했습니다.
아래 이미지는 DB에 반영되어있는지, mysql workbench 를 통해 확인하였습니다.
아직, ERD에 작성한 모든 테이블을 models 폴더에 만들지 못했습니다. 현재는 User 테이블만 존재합니다.
bcrypt, crypto 의 차이점에 대해서 추후 조원들과 얘기를 나눠보고 싶습니다.
refreshToken 에 대해 필요한지, 추가할지 의논해봐야 합니다.

[#5] 백엔드 프로젝트 구조 잡기 완료

---

client/src/components/base/appbar/index.scss
client/src/components/base/appbar/index.ts
client/src/components/sample.ts
client/src/core/component.ts
client/src/core/router.ts
client/src/index.html
client/src/main.ts
client/src/pages/calendar.ts
client/src/pages/home.ts
client/src/pages/statistics.ts
client/webpack.config.js

> 페어프로그래밍으로 작업했습니다.
클라이언트 라우터 기능 및 프로젝트 구조
ㅈㄱㄴ
https://user-images.githubusercontent.com/86946740/127290550-f2e22be0-a215-405e-ba2d-099df15dc453.mov

[#4] 클라이언트 구조 잡기

---

client/src/components/base/fab/index.ts
client/src/index.html
client/src/main.ts
client/src/utils/api.ts
client/src/utils/select.ts

> 페어프로그래밍을 통해 진행했습니다.
회원가입 구현 및 프론트엔드 구조 잡기
API 를 제작했습니다.
회원가입 폼 제작 후, 해당 값들을 서버의 API를 통해 전달해서 DB에 성공적으로 추가되는지 확인했습니다.
https://user-images.githubusercontent.com/86946740/127325611-1101fef4-4498-4832-a6cb-b7b65227183d.mov

[#4, #6] 회원가입 구현 및 프론트엔드 구조 잡기

---

client/src/components/base/appbar/index.ts
client/src/components/sample.ts
client/src/core/component.ts
client/src/core/observable.ts
client/src/main.ts
client/src/models/date-store.ts
client/src/models/index.ts
client/src/pages/home.ts

> 페어프로그래밍으로 진행했습니다.
closes #4 
- 스토어 추가 및 테스트를 진행했습니다. 
https://user-images.githubusercontent.com/86946740/127350355-545d513f-6773-46e5-ad66-16b8defe472e.mov
까지 테스트
https://user-images.githubusercontent.com/86946740/127350492-2d6c7975-58c1-4cad-917e-81dcb599b64e.mov
store 를 어디까지 만들어야 하는지, 의논이 필요합니다.

[#4] 프론트엔드 구조 잡기 완성~~ 이얏호

---

server/src/constants/common.js
server/src/models/category.js
server/src/models/history.js
server/src/models/index.js
server/src/models/pay-type.js
server/src/models/user-pay-trend.js
server/src/models/user-pay-type.js

> 28일까지는 페어프로그래밍으로 진행했습니다. 29일 오전에 따로 작업했습니다.
> 오늘 한 커밋에 대해서만 리뷰해주시면 될것 같습니다! 
ㅈㄱㄴ
ㅈㄱㄴ
다음은 DB에서 뽑아낸 ERD입니다.
history 테이블과 User, Category, PayType 테이블들과의 관계를 따로 맺는 것인지, 같이 맺어줘야하는건지 고민해봐야 할 것 같습니다!

[#5] timezone 설정 완성~~

---

client/src/components/base/appbar/index.scss
client/src/components/base/appbar/index.ts
client/src/core/observable.ts
client/src/core/router.ts
client/src/main.ts
server/src/routes/home-router.js
server/src/routes/index.js
server/src/services/history-service.js

appbar 작업중
appbar ui , 페이지이동, 서버 home route 생성
https://user-images.githubusercontent.com/47776356/127444048-bc0ec276-b039-482b-bd4b-39e15f2ae0e0.mov

I10 appbar 현재까지 작업한 내용

---

client/src/components/base/fab/index.scss
client/src/components/base/fab/index.ts
client/src/components/base/modal/index.scss
client/src/components/base/modal/index.ts
client/src/index.html
client/src/main.ts
client/src/utils/selectHandler.ts

모달 띄우기 및 회원가입 처리
모달 띄우기 및 회원가입 입력을 모달에서 받도록 처리했습니다.
https://user-images.githubusercontent.com/86946740/127444460-94372c3e-f1e3-4d63-bee8-97ec5bd289cf.mov

회원가입 기능 추가

---

client/src/components/base/user-modal/modal-content/index.ts
client/src/utils/cookie.ts
server/src/constants/error.js
server/src/constants/success.js
server/src/services/user-service.js
server/src/utils/jwt.js

[#7] 로그인 요청 후 정상적인 응답 왔을때 처리 추가
https://user-images.githubusercontent.com/86946740/127483684-cc9b54d0-50cf-4841-8ccf-61f11c32d2a0.mov
closes #7
resolves #7

[#7] 로그인 수정

---

client/src/components/base/appbar/index.scss
client/src/components/base/appbar/index.ts
client/src/components/calandar/content/index.scss
client/src/components/calandar/content/index.ts
client/src/components/calandar/daybar/index.scss
client/src/components/calandar/daybar/index.ts
client/src/components/calandar/footer/index.ts
client/src/components/calandar/index.scss
client/src/index.scss
client/src/pages/calendar.ts

캘린더 페이지 작업
날짜(일~월) 바 , 달력 ui 작업, 스토어 변경에 따른 달력 변경 , appbar의 scss와 루트 index.scss 변경

I18 calendar

---

client/src/components/base/user-modal/modal-content/index.ts
client/src/components/home/searchbar/index.scss
client/src/components/home/searchbar/index.ts
client/src/pages/home.ts
server/src/middlewares/decode-jwt.js
server/src/routes/home-router.js
server/src/services/category-service.js
server/src/services/history-service.js
server/src/services/user-pay-type-service.js

#15 
https://user-images.githubusercontent.com/86946740/127562183-c508c5fa-540b-41a3-ab0a-d49c756e018b.mov

메인 페이지 데이터 조건 검색창 구현

---

client/package.json

[#15] bugs: :bugs: node sass 문제로 sass 로 변경

---

client/webpack.config.js
server/src/models/index.js
server/src/models/pay-type.js

#48
> DB 관계를 잘못 맺어서 수정했습니다.
> 이전에 작업하고 추가되지 않은 웹팩 설정은 덤입니다.. 핳
> 핫픽스 하면서, 개인적으로 wiki에 담고 싶은 내용이 많았네요. 제 실수담을 꼭 wiki에 옮겨 두겠습니다.

[#48] DB 구조 수정

---

client/src/components/base/appbar/index.ts
client/src/components/base/daily-history/index.ts
client/src/components/base/user-modal/modal-content/index.ts
client/src/components/calandar/content/index.ts
client/src/core/router.ts
client/src/models/date-store.ts
client/src/utils/cookie.ts

checkLogin, 라우팅, datastore
checkLogin 함수를 추가하고, 라우팅, api호출 등 적용하였습니다.

[#7] checkLogin, 라우팅, datastore

---

client/src/components/base/appbar/index.ts
client/src/components/base/daily-history/index.ts
client/src/components/base/user-modal/modal-content/index.ts
client/src/components/calandar/content/index.ts
client/src/core/router.ts
client/src/models/date-store.ts
client/src/utils/cookie.ts

Revert "[#7] checkLogin, 라우팅, datastore"

---

client/src/components/base/appbar/index.ts
client/src/components/base/daily-history/index.ts
client/src/components/base/user-modal/modal-content/index.ts
client/src/components/calandar/content/index.ts
client/src/core/router.ts
client/src/models/date-store.ts
client/src/utils/cookie.ts

Reverts woowa-techcamp-2021/cashbook-11#52

Revert "Revert "[#7] checkLogin, 라우팅, datastore""

---

client/src/components/base/user-modal/modal-content/index.scss
client/src/components/base/user-modal/modal-content/index.ts
client/src/components/calandar/content/index.scss
client/src/components/calandar/content/index.ts
client/src/core/router.ts
client/src/models/date-store.ts
client/src/pages/callback.ts
client/src/utils/comma.ts
server/package.json
server/src/routes/index.js
server/src/routes/oauth-router.js
server/src/services/oauth-service.js

깃허브 로그인 구현
callback  page를 만들고, 깃허브 로그인 기능을 추가했습니다.
https://user-images.githubusercontent.com/47776356/127755970-c9bf63e2-9c10-46a0-95b1-7fad51c51d4b.mov
env 파일 변경있으니, 꼭 적용해주세요~
메인 화면에서 로그인 해주세요 스낵바 뜨는 문제는 고쳐두셨다고 해서 건들이지 않았습니다.
local과 github 유저가 같을 때에 대해서 추후에 고민해보았으면 합니다.

[#7] signin

---

client/src/components/base/appbar/index.ts
client/src/components/calandar/content/index.ts

달력
- 달력에  금액 3자리마다 , 표시 했습니다.
- 일관성 있는게 좋을 것 같아서 합계 금액은 항상 표시하도록 했습니다. (하늘색)
클릭했을 때 해당날짜 히스토리 모달로 뜨는 기능에 대해서, 아직 구현하지 않았습니다. 이유는,
1. 기존 모달을 사용하면 복잡성이 높아져서 버그가 발생할 것 같아요.
2. 모달을 새로만들자니 기존 모달에 있었던 문제인 opacity 라던가, 또 전역에 히스토리전용 모달을 만들어야 할지 등 고민이 있네요.
3. 메인의 컴포넌트가 완성되고 그것을 쓰는게 좋을 것 같아 하게 된다면 메인 컴포넌트가 완성되고 해야할 것 같아요.
4. 추가적인 기능이므로 차트를 먼저 그리고 이후에 하는게 좋다는 생각입니다.

[#18] calendar

---

client/src/components/base/appbar/index.ts
client/src/components/base/fab/index.scss
client/src/components/base/fab/index.ts
client/src/components/base/month-history/daily-history/index.ts
client/src/components/base/month-history/daily-history/unit-history/index.scss
client/src/components/base/month-history/daily-history/unit-history/index.ts
client/src/components/base/month-history/index.ts
client/src/components/base/user-modal/modal-content/index.ts
client/src/components/home/content/add-history/index.ts
client/src/components/home/content/filter/index.ts
client/src/components/home/content/index.ts
client/src/components/home/searchbar/index.scss
client/src/components/home/searchbar/index.ts
client/src/models/date-store.ts
client/src/utils/util-func.ts
server/src/constants/error.js
server/src/services/history-service.js
server/src/services/oauth-service.js
server/src/utils/make-query.js
server/src/utils/result-checker.js
server/src/utils/util-func.js

메인 페이지를 보완했습니다.
1. 검색기능 날짜 수정 : 이전에는 한달 이내의 내역만 가능했으나, 검색범위를 넓힘.
2. 로그인 전후로 플로팅 버튼에 에니메이션 및 비로그인시 추가버튼 안보이도록 수정
3. 버그 수정 : unit history 가 hover 된 상태에서 아래로 스크롤시, appbar 위로 나오는 버그 수정
4. 히스토리 추가시, 탐색바의 유저의 결제수단 갱신
5. 깃헙 로그인 버그 수정
6. 서버 유틸함수 버그 수정
7. 히스토리 추가 및 삭제 기능 보완 ( UserPayType, UserPayTrend에 반영되도록 수정 )

메인 페이지 보완 및 unsubscribe 문제로 인한 버그 수정을 위한 코드 병합 PR

---

client/src/components/base/appbar/index.scss
client/src/components/base/appbar/index.ts
client/src/components/base/fab/index.scss
client/src/components/base/user-modal/modal-content/index.ts
client/src/components/home/content/index.scss
client/src/components/home/searchbar/index.scss
client/src/components/home/searchbar/index.ts
client/src/index.html
client/src/index.scss
client/src/main.ts
client/src/pages/callback.ts
client/src/pages/home.ts

[#67] wip: :gear: 공통적인 레이아웃 작업 완료

---

client/src/components/home/content/filter/index.ts
client/src/pages/callback.ts
server/src/app.js
server/src/middlewares/log.js

[#67] wip: :gear: 서버 로그작업 및  이미지 경로 수정

---

client/src/components/base/user-modal/modal-content/index.ts

[#67] wip: :gear: 이미지 src 누락
